mysql:
  path:
  config:
  db-name:
  username:
  password:
  max-idle-conns: 0
  max-open-conns: 0
system:
  port: 8888
  success-code: 1
  success-message: 操作成功
  error-code: 0
  error-message: 操作失败
upload:
  avatar-save-path: upload/avatar
  avatar-url: avatar
  file-save-path: upload/file
  file-url: file
  web-logo-save-path: upload/logo
  web-logo-url: logo
  banner-image-save-path: upload/banner
  banner-image-url: banner
zap:
  prefix: 【gin-quasar-admin】
  level: info
  filepath: log
  filename: gqa-log
  max-size: 200
  max-age: 8
  max-backups: 10
